# -*- coding: utf-8 -*-
"""JogoDaVelha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18NNkOs9bboJ7fDVoP03QHj_hGB_hleJk
"""

def imprimir_tabuleiro(tabuleiro):
    print("\n")
    print(f" {tabuleiro[0]} | {tabuleiro[1]} | {tabuleiro[2]} ")
    print("-----------")
    print(f" {tabuleiro[3]} | {tabuleiro[4]} | {tabuleiro[5]} ")
    print("-----------")
    print(f" {tabuleiro[6]} | {tabuleiro[7]} | {tabuleiro[8]} ")
    print("\n")

def verificar_vitoria(tabuleiro, jogador):
    vitorias = [
        [0, 1, 2], [3, 4, 5], [6, 7, 8],
        [0, 3, 6], [1, 4, 7], [2, 5, 8],
        [0, 4, 8], [2, 4, 6]
    ]
    for condicao in vitorias:
        if tabuleiro[condicao[0]] == tabuleiro[condicao[1]] == tabuleiro[condicao[2]] == jogador:
            return True
    return False

def jogo_da_velha():
    tabuleiro = [str(i) for i in range(1, 10)]
    jogador_atual = "X"
    jogadas = 0

    print("=== BEM-VINDO AO JOGO DA VELHA ===")
    print("Escolha uma posição de 1 a 9 conforme o tabuleiro abaixo:\n")

    while jogadas < 9:
        imprimir_tabuleiro(tabuleiro)

        try:
            escolha = int(input(f"Jogador {jogador_atual}, escolha sua posicao (1-9): "))
            indice = escolha - 1

            if indice < 0 or indice > 8 or tabuleiro[indice] in ["X", "O"]:
                print("Posicao invalida ou ja ocupada! Tente novamente.")
                continue
        except ValueError:
            print("Por favor, digite um numero valido entre 1 e 9.")
            continue

        tabuleiro[indice] = jogador_atual
        jogadas += 1

        if verificar_vitoria(tabuleiro, jogador_atual):
            imprimir_tabuleiro(tabuleiro)
            print(f"Parabens! O Jogador {jogador_atual} venceu o jogo!")
            return

        jogador_atual = "O" if jogador_atual == "X" else "X"

    imprimir_tabuleiro(tabuleiro)
    print("Deu velha! O jogo terminou Empatado.")

if __name__ == "__main__":
    jogo_da_velha()